version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer  # Match the name in your properties file
    ports:
      - "3307:3306"
    networks:
      - tp-foyer-net

  spring-boot-app:
    image: sarra7/nginx:latest  # Make sure this is the correct Spring Boot image
    container_name: nginx-container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-container-new:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - mysql
    networks:
      - tp-foyer-net

networks:
  tp-foyer-net:
    driver: bridge
