# Configuration de la base H2
spring.datasource.url=jdbc:h2:mem:foyer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2 activée et accessible via le bon path
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Port et contexte
server.port=8082
server.servlet.context-path=/Foyer
